name: setup-test-lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: make setup
      - run: make test
      - run: make lint
